<?php
include_once APP_PATH . '/assets/header.php';
?>
<form action="productadd" method="post">
    <label>Product Name</label>
    <input type="text" name="name" class="form-control">
    <label>Product Quantity</label>
    <input type="number" name="qty" class="form-control">
    <label>Product Price</label>
    <input type="number" name="price" class="form-control">
    <label>Product Description</label>
    <input type="text" name="desc" class="form-control">
    <label>choose img</label>
    <input type="text" name='file' class='form-control'>
    <br><br>
    <input type="submit" value="submit" class='btn btn-primary'>
</form>
